---
title: "Temuulen Enebish's CV"
author: Temuulen Enebish
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css: ['css/styles.css', 'resume']
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
---

```{r, include=FALSE}
knitr::opts_chunk$set(
  results = 'asis', 
  echo = FALSE
)

library(glue)
library(tidyverse)

# ======================================================================
# These variables determine how the the data is loaded and how the exports are
# done.

# Is data stored in google sheets? If no data will be gather from the csvs/
# folder in project
using_googlesheets <- TRUE

# Just the copied URL from the sheet
positions_sheet_loc <- "https://docs.google.com/spreadsheets/d/1ddZJQ2B079gxkbflJpVWIDi3eHoT56Nadno8L8AazkM"

# Is this sheet available for anyone to read? If you're using a private sheet
# set this to false and go to gather_data.R and run the data loading manually
# once to cache authentication
sheet_is_publicly_readable <- TRUE

# Is the goal of this knit to build a document that is exported to PDF? If so
# set this to true to have links turned into footnotes at the end of the
# document
PDF_EXPORT <- TRUE


CV_PDF_LOC <- "https://github.com/temuulene/cv/raw/master/temuulen_cv.pdf"
CV_HTML_LOC <- "https://temuulen.name/cv/"


# A global (gasp) variable that holds all the links that were inserted for
# placement at the end
links <- c()

# ======================================================================
# Now we source two external scripts. One contains functions for building the
# text output and the other loads up our data from either googlesheets or csvs

# Functions for building sections from CSV data
source('parsing_functions.R') 

# Load data for CV/Resume
source('gather_data.R')
```



```{r}
# When in export mode the little dots are unaligned, so fix that. 
if (PDF_EXPORT) {
  cat("
  <style>
  :root{
    --decorator-outer-offset-left: -6.5px;
  }
  </style>")
}
```


Aside
================================================================================

Contact {#contact}
--------------------------------------------------------------------------------

```{r}
contact_info %>% 
  glue_data("- <i class='fa fa-{icon}'></i> {contact}")
```



Language Skills {#skills}
--------------------------------------------------------------------------------

```{r}
build_skill_bars(skills)
```



Disclaimer {#disclaimer}
--------------------------------------------------------------------------------

Made with the R package [**pagedown**](https://github.com/rstudio/pagedown). 

The source code is available at [github.com/temuulene/cv](https://github.com/temuulene/cv).

Last updated on `r Sys.Date()`.



Main
================================================================================

Temuulen Enebish {#title}
--------------------------------------------------------------------------------

Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'education')
```



Research Experience {data-icon=laptop}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'research_positions')
```



Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'industry_positions')
```

<!-- These breaks just force a new page so section doesnt get cut off -->

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'teaching_positions')
```

Selected Publications and Posters {data-icon=book}
--------------------------------------------------------------------------------

```{r}
print_section(position_data, 'academic_articles')
```

```{r}
if (PDF_EXPORT) {
  cat(
    "
Links {data-icon=link}
--------------------------------------------------------------------------------
"
  )
  
  walk2(links, 1:length(links), function(link, index) {
    print(glue('{index}. {link}'))
  })
}
```


